name: CI Check (Lint + Build)

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ✅ 수동으로 pnpm 설치
      - name: Install pnpm
        run: |
          npm install -g pnpm@10.13.1
          pnpm -v

      # ✅ 의존성 설치
      - name: Install dependencies
        run: pnpm install

      # ✅ ESLint 실행
      - name: Run ESLint and prettier check
        run: pnpm lint && pnpm prettier --check .

      # ✅ 빌드 실행
      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
